name: Latest blogs activity
on:
  schedule:
    # Runs once every 7 days (at 00:00 UTC on Sunday)
    - cron: '0 0 * * 0'
  workflow_dispatch:
permissions:
  contents: write
  
jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from WebSite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "hhkmyid"
          commit_message: "Updated readme with the latest feed"
          max_post_count: 10
          feed_list: "https://hhk.my.id/posts/index.xml"
          template: "&emsp;&emsp;📖 <a href='$url' target='_blank'>$title</a><br>"
