name: 'Update README'

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  recent-activity:
    name: 'Update README with latest activity'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Update README.md from TEMPLATE.md'
        uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
